
##CONSUMER_BEHAVIOUR_ANALYSIS

#What is total revenue generated by male vs female
select gender, sum(purchase_amount)  as total_revenue_generated from customer group by gender;

#which customers used discount but paid more than avg price
select * from customer;
select customer_id,purchase_amount from customer
where discount_applied = "Yes" and purchase_amount >= (select avg(purchase_amount) from customer);

#which are the top 5 products with the highest avg review rating
select item_purchased, round(avg(review_rating),2) as "Avg product rating"
from customer
group by item_purchased
order by avg(review_rating) desc limit 5;

#compare the avg purchase amount between satndard and express shipping
select round(shipping_type,2),avg(purchase_amount) from customer 
where shipping_type in ('Standard','Express') 
group by shipping_type ;

#Do the subscriber customers spend more? compare average spend and total revenue between subscribers and non-subscribers
select subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue from customer
group by subscription_status
order by total_revenue, avg_spend desc;

#which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
round(sum(case when discount_applied = 'Yes' THEN 1 ELSE 0 end)/count(*) * 100,2) as discount_rate 
from customer
group by item_purchased
order by discount_rate desc
limit 5;

#Segment customers into New, Returning, and loyal based on their total
-- number of previous purchase, and show the count of each seagment
with customer_type as (
select customer_id, previous_purchases,
case
	when previous_purchases = 1 then 'Now'
    when previous_purchases between 2 and 10 then 'Returning'
    else 'Loyal'
    end as customer_segment
from customer
)

select customer_segment, count(*) as "Number of customers"
from customer_type
group by customer_segment;

#What are the top 3 most purchased produucts within each category
with item_counts as (
select category, 
item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category  order by count(customer_id) desc) as item_rank
from customer
group by category,item_purchased)

select item_rank, category, item_purchased, total_orders
from item_counts where item_rank <= 3;

#Are customers who are repeat buyers (more than 5 orevious_purchases) also likely to subscribe
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status;

#what is the revenue contributuion of each row group?
select age,
sum(purchase_amount) as total_revenue
from customer
group by age
order by total_revenue desc;



